image:
  repository: ghcr.io/p3l1/paperless-ngx-operator
  # Defaults to the chart's appVersion.
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

crds:
  install: true

replicaCount: 1

leaderElection:
  enabled: true

serviceAccount:
  create: true
  name: ""
  annotations: {}

rbac:
  create: true

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 256Mi

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: [ALL]

nodeSelector: {}
tolerations: []
affinity: {}
podAnnotations: {}
